FROM golang:1.25-alpine AS build
RUN GOFLAGS="-tags=no_clickhouse,no_libsql,no_mssql,no_mysql,no_sqlite3,no_vertica,no_ydb -ldflags=-s -w" \
    go install github.com/pressly/goose/v3/cmd/goose@v3.24.1
RUN test -s /go/bin/goose

FROM alpine:3.21
RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/goose /usr/local/bin/goose
RUN test -s /usr/local/bin/goose
COPY database/migrations /migrations
ENTRYPOINT ["goose", "-dir", "/migrations", "postgres"]
